#+TITLE: Clerk.io Pixel and Widget Injection for Wix
#+AUTHOR: Alexander Bugge Stage
#+EMAIL: abs@clerk.io

#+DESCRIPTION: Guide document for implementing Clerk.io in Wix's React based WYSIWYG editor.
#+KEYWORDS: wix, clerk.io, ecommerce, personalization, search, recommendations, embedcode, injection
#+LANGUAGE: en

* Structure and Design

The Wix editor is made using React, and likewise the frontend for it also renders the site using React components.
This poses a few restrictions in terms of data acccess while also imposing limits on how you can interact with information on the page.

As a result the code for Clerk is segmented in 4 main sections:

- Affiliate tracking script.
_{ Clerk.js, located in a field outside the Editor or Theme }

- Utility Functions
_{ Utility function library located in the Theme "public" resource }

- Custom element scripts.
_{ A number of custom-element.js files located in the Theme "public/custom-elements" resource  }

- Element hydration scripts.
_{ A number of snippets placed in the appropriate controllers page.js file which hydrate elements with contextual data before hydration }

* Utility Functions

In order to keep the setup organized all functions used to retrieve contextual data, are stored in "public/clerk-wix.js".

These functions are imported in the element hydration scripts, in order to populate data before Clerk initialization.

clerkGetCart()
_{ gets cart object, contextually agnostic }
#+BEGIN_SRC javascript
export const clerkGetCart = async () => {
    const currentCart = await cart.getCurrentCart();
    const cartInfo = { cartId: currentCart._id, cartLineItems: currentCart.lineItems }
    return cartInfo;
}
#+END_SRC

clerkGetCartProducts()
_{ gets product ids in cart, contextually agnostic }
#+BEGIN_SRC javascript
export const clerkGetCartProducts = async () => {
	const cart = await clerkGetCart();
    const product_ids = cart.cartLineItems.map(line_item => {
        return line_item?.productId
    });
	return product_ids;
}
#+END_SRC

clerkGetQuery()
_{ gets gets value of q param if present, contextually agnostic }
#+BEGIN_SRC javascript
export const clerkGetQuery = (wixLocation) => {
	return wixLocation.query['q'];
}
#+END_SRC


* Components

* Implementation

* Debugging

* References